name: "posts-website"

services:
  frontend:
    image: "posts-website-frontend-dev"
    build:
      target: dev
    ports: 
      - 5173:5173
    volumes:
      - type: bind
        source: ./Client/src
        target: /app/src
      - type: bind
        source: ./Client/package.json
        target: /app/package.json
      - type: bind
        source: ./Client/package-lock.json
        target: /app/package-lock.json
    extends:
      file: compose.yaml
      service: frontend
  api:
    extends:
      file: compose.yaml
      service: api
  db:
    extends:
      file: compose.yaml
      service: db