name: "posts-website"

services:
  frontend:
    container_name: posts-website-frontend
    build:
      context: ./Client
  api:
    container_name: posts-website-api
    build: 
      context: ./Server
      target: final
    ports:
      - 8080:8080
    depends_on: 
      - db
  db:
    container_name: posts-website-db
    image: "postgres:alpine3.19"
    expose:
      - 5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password